language: python

python:
  - '3.6'

branches:
  only:
  - master
  - devel
  - unstable

env:
  EMAILPWD = ''

install:
  - pip install -r requirements.txt
  - python3 manage.py make_db
  - python3 manage.py load_db
  - python3 manage.py load_all

services:
  - docker

script:
  - python3 manage.py test_report
  - python3 manage.py check_general
  - python3 manage.py check_stylesheet


